### PR TITLE
Need to spin another workflow-multibranch

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees URGENT @rtyler

### CODE REVIEW

**Comment by daniel-beck** [comment]
This looks like it will result in plenty of unsatisfied dependencies…?

**Comment by stephenc** [comment]
@daniel-beck we need to roll 2.12 and we want to hold it back from the UC until Blue Ocean is done

**Comment by daniel-beck** [comment]
What's broken about this?

**Comment by stephenc** [comment]
2.11 is failing blue ocean tests
2.11-beta-1 wasn't
So we need to revert / fix the change in 2.11-beta-1...2.11 which will require a new release

**Comment by daniel-beck** [comment]
Future release for a bugfix needs preemptive block.

**Pull request merged**
