### PR TITLE
Escape all the entities

### PR DESCRIPTION
**Pull request by daniel-beck**
@rtyler @jglick

### CODE REVIEW

**Comment by batmat** [comment]
:+1:

**Comment by rtyler** [comment]
Once @jglick signs off I think we can mergey merge

**Comment by daniel-beck** [comment]
@rtyler Are we sure we need to wait? Worst case, I'll open a third PR for this line :laughing:

**Comment by rtyler** [comment]
WHAT COULD POSSIBLY GO WRONG

**Pull request merged**
