### PR TITLE
Deprecate blackduck-installer

### PR DESCRIPTION
**Pull request by jrichardBD**
We are no longer supporting this plugin and it does not work with the current version of the update-sites-manager plugin, so we would like to remove it from the list of available plugins

### CODE REVIEW

**Comment by batmat** [comment]
Why are there 3 commits instead of one?

**Comment by jrichardBD** [comment]
They are 3 instead of one because I made the change and accidentally changed the .gitignore file, so I reverted the change and then made the change to the artifact-ignores.properties file again.

**Comment by batmat** [comment]
In that case, in general you want to squash your commits or something. And in general, you also want to create a dedicated branch for each PR, that prevents you from adding unwanted commits to running PRs (didn't you have a similar _issue_ some time ago btw?)

**Comment by jrichardBD** [comment]
OK, would you like to decline this PR and I will create a cleaner one? Or is this one line change alright?

**Comment by batmat** [comment]
I don't have karma to handle that repository anyway. @rtyler did it.

Anyway, for the future, you may want to learn about rebasing and history rewriting in general with `Git`. It's very useful and helps keeping a readable history.

Cheers

**Comment by jrichardBD** [comment]
I am sorry for the confusion and I will make sure any future requests are readable and clean.
Thank you!

**Pull request merged**
