### PR TITLE
ignore openstack-plugin as it is renamed to openstack-cloud

### PR DESCRIPTION
**Pull request by mavlyutov**

### CODE REVIEW

**Comment by daniel-beck** [comment]
So far there has been no release of `openstack-cloud`, is this deliberate?

Do you know what https://github.com/jenkinsci/openstack-plugin is?

I'd also like to create an issue tracker component for your plugin. Let me know the component lead's jenkins-ci.org username and I'll create a component on issues.jenkins-ci.org.

**Comment by mavlyutov** [comment]
builds: https://jenkins.ci.cloudbees.com/job/plugins/job/openstack-cloud-plugin/
artifacts: http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/openstack-cloud/
so, as I see there's already two releases - I built em today

It would be great if you create jira-component, Ill add it to wiki-page then

P.S. and I dont know what https://github.com/jenkinsci/openstack-plugin is
I renamed my plugin to be more self-descriptive, cause I found that strange repo too

**Comment by daniel-beck** [comment]
Right, now they showed up on http://updates.jenkins-ci.org/download/plugins/openstack-cloud/

I'll need the user name on jenkins-ci.org (used for wiki, issue tracker, uploading artifacts) for the user who will be default assignee for new issues before I can create the component.

**Comment by mavlyutov** [comment]
ye, forget about the username =)
default assignee should be ```mavlyutov```

**Comment by daniel-beck** [comment]
IRC bot we use for this is currently on strike. I'll do it once he's back.

**Pull request merged**
