### PR TITLE
Return SCM APi 2.0.x and friends to Update Center

### PR DESCRIPTION
**Pull request by stephenc**
go2

@reviewbybees

### CODE REVIEW

**Comment by daniel-beck** [comment]
@stephenc So… can be merged now or what?

**Comment by stephenc** [comment]
@daniel-beck https://github.com/jenkins-infra/jenkins.io/pull/580 needs to be merged and published first... but once that is public we are good to go on this one

**Comment by rtyler** [comment]
@stephenc I disagree, the site is rebuilt very quickly, whereas Update Center information takes a couple of hours to propagate. if we publish the blog post(s) first then users won't be able to see anything for quite some time

**Comment by stephenc** [comment]
@rtyler ok, I defer to your judgement. If you would rather merge this first we are 👍

**Pull request merged**
