### PR TITLE
Remove HiddenParameter

### PR DESCRIPTION
**Pull request by daniel-beck**
As requested on https://groups.google.com/d/msg/jenkinsci-dev/Vxu26M5O2Ms/-g8hj_0XzXwJ

### CODE REVIEW

**Comment by orrc** [comment]
:+1:

**Comment by wy-scm** [comment]
How can I merge?those two plugins is mime.

**Comment by orrc** [comment]
@wy-scm Daniel (who has commit access) will merge it soon.

**Comment by wy-scm** [comment]
thanks

**Pull request merged**
