### PR TITLE
Code quality fix - Resources should be closed.

### PR DESCRIPTION
**Pull request by faisal-hameed**
This pull request is focused on resolving occurrences of Sonar rule 
squid:S2095 - Resources should be closed.
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2095

Please let me know if you have any questions.

Faisal Hameed

### CODE REVIEW

**Comment by batmat** [comment]
+0.8.

It's definitely an improvement. But if we touch that, then I'd recommend to simplify the code and use Java 7's try-with-resources instead (just checked and the job already runs with Java 7, so that would not be an issue).

**Comment by faisal-hameed** [comment]
@batmat Where I can find the jdk requirement for this project? 
Is it minimum jdk7?

**Comment by batmat** [comment]
Yes. The build is using jdk7 as I said.
Le 3 mars 2016 11:18 AM, "Faisal Hameed" <notifications@github.com> a
écrit :

**Comment by faisal-hameed** [comment]
@batmat Updated with try-with resource.

**Comment by batmat** [comment]
Nice! Thanks!

:+1:

**Comment by batmat** [comment]
Ping @daniel-beck or @orrc to merge ?

**Comment by daniel-beck** [comment]
Believing everything @batmat tells me (at least about JDK 7 :wink: ).

**Comment by daniel-beck** [comment]
[And I probably shouldn't…](https://github.com/jenkinsci/pom/blob/jenkins-1.26/pom.xml#L566)

Backing out…

**Comment by batmat** [comment]
Yup forgot about it. Only checked the JDK used in the job and thinking the versions were aligned.

**Pull request merged**
