### PR TITLE
Remove some outdated wiki overrides

### PR DESCRIPTION
**Pull request by batmat**
First batch. I'll try and process the list below later. Btw I think trying to put a dedicated comment each time is useful (has been here to double-check at least). Let me know if you think this is OK this way, or should better be one PR per removal.

### CODE REVIEW

**Comment by orrc** [comment]
Nice! Thanks

You can definitely do everything in one PR.  So long as there are commit messages like you have just now (e.g. `Wiki override for <artifact-id> is no longer needed`), this looks good :+1:

**Comment by abayer** [comment]
Ping here when you're ready to merge?

**Comment by batmat** [comment]
Yup, FTR, as @orrc says I can do it a one PR, I'm indeed processing the list and will push commits and say when ready to review/merge. 

Retitling with WiP in the meantime.

**Comment by abayer** [comment]
Sounds good!

**Comment by batmat** [comment]
@orrc @abayer Done!

**Comment by batmat** [comment]
+ I rebased on the latest commit (@abayer's famous one :))

**Comment by abayer** [comment]
:+1: to me, but @orrc, let's get your opinion. =)

**Comment by orrc** [comment]
:+1:

**Comment by abayer** [comment]
And merged!

**Comment by batmat** [comment]
Cool. Thanks
Le 29 déc. 2015 11:38 PM, "Andrew Bayer" <notifications@github.com> a
écrit :

**Pull request merged**
