### PR TITLE
[WIP] Remote Repositories

### PR DESCRIPTION
**Pull request by ghost**
This would allow people to specify a repository other than the Jenkins repo. You can specify a local directory or a remote repository.

### CODE REVIEW

**Comment by daniel-beck** [comment]
This PR looks messed up. Could you try to e.g. rebase it to get rid of the unrelated commits, and exclude the formatting changes from it to facilitate reviewing?

**Comment by JamesRichard** [comment]
Hello,
Which commits do you think should be excluded? Where would you suggest it
be rebased to?

If you can provide this information and reject my pull request, I will
update the code with the changes that I would like and create a new pull
request when I get the chance.  Unfortunately I am tied up in another
project right now so it may be a while before I get back to this.

Thank you for the response!

-James Richard Jr
jamesrichard91@gmail.com
(203) 814-8774

**Comment by daniel-beck** [comment]
@JamesRichard 

Sorry about the late response!

> Which commits do you think should be excluded? Where would you suggest it be rebased to?

There are merges of other pull requests in the list of commits for this PR. I don't know, just looks messed up. Only 4 of 35 commits associated with this PR seem to be original to this PR.

Please also note that this PR no longer merges cleanly, likely due to the changes we implemented on June 1 (requiring wiki URLs in plugins).

Could you update this PR to:

* only include relevant commits (possibly having to re-do them on a new branch based on current master, I don't know), 
* merge cleanly on current master, 
* and not include any unnecessary whitespace changes? For example, 4bdf6d53c484113f59f7956a58caf4bacf9bdf0d contains no actual changes to `MavenRepositoryImpl.java` other than whitespace.

**Comment by daniel-beck** [comment]
@JamesRichard Please also note that any further commits to the source branch of this PR will be added to it automatically. Your commit from three days ago appears to be unrelated to the purpose of this PR.

**Comment by daniel-beck** [comment]
Marking this PR as work in progress pending outstanding review comments that need to be addressed.

**Comment by batmat** [comment]
I _think_ this PR needs to be closed and potentially be reissued on a dedicated branch.

@jrichardBD beware than doing a PR on master is generally not recommended since any new commit (like the new ones from yesterday...) will be added to the PR...

**Comment by jrichardBD** [comment]
I agree with batmat, this PR should be closed and not merged into master.  This PR was not fully thought out and I have not had time to fix the merging issues or rebase it properly.

**Comment by batmat** [comment]
Ping @daniel-beck can you close this one as requested by the PR author? Thanks

**Comment by batmat** [comment]
Or, now that I think of it, @jrichardBD actually you could close it yourself.

**Comment by batmat** [comment]
Thanks Christopher.

**Pull request closed without merging**
