### PR TITLE
Remove unknown release of build-timeout

### PR DESCRIPTION
**Pull request by daniel-beck**
Thanks to @oleg-nenashev

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
👍 but actually thanks to @bsideup

**Comment by bsideup** [comment]
Would be great to hear some postmortem about it. 

Was confused to found non-existing release (i.e. no tags in the code repository) :)

Also, exactly the reason why I created http://github.com/jucies/releases - to make it clear as hell where releases come from and associate them 1-to-1 with a code :D

**Comment by oleg-nenashev** [comment]
I suppose @HedAurabesh was doing an internal release with fixes from the master and then messed up something in his Maven config. CC @ikedam

**Comment by ikedam** [comment]
Can't we see who uploaded the version from access logs?

**Comment by oleg-nenashev** [comment]
@ikedam See my comment above. It has been uploaded by @HedAurabesh

**Comment by ikedam** [comment]
@oleg-nenashev Oh, you saw that from access logs. Thanks!

@HedAurabesh
Please have a separate environment to make private releases (e.g. another computer, or another  OS user, without credentials to the update center). It prevent you from uploading private releases to the update center accidentally.

**Comment by oleg-nenashev** [comment]
@ikedam Just in case it happens again, it's possible to diagnose this issue using Artifactory. https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/General/releases/org/jenkins-ci/plugins/build-timeout/1.16-INTEL-1

**Comment by ikedam** [comment]
@oleg-nenashev It's really useful! Thank you.

**Pull request merged**
